name: Deploy Laravel Application

on:
  push:
    branches:
      - master  # Adjust the branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Lightsail Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 13.43.246.149
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /opt/bitnami/apache2/htdocs
            ./deploy.sh
